### ISSUE TITLE
Reddit video support

### ISSUE THREAD

**Issue by Atte** [BTDev/BerryTube#5]
Example courtesy of Kris321: https://v.redd.it/8lukdvw6sti11

Probably should just allow queues by link to the thread.

**Comment by Smidqe** [comment]
Leaving this here before I forget again. Did digging around and found rather simple method for implementing this.

For thread URL's:
Appending `.json` to end of the url of the reddit thread will give a JSON response. 

For example:
https://www.reddit.com/r/Animemes/comments/9ayd4s/woof/.json

In that JSON response there's a `media -> reddit_video` block with url's for DASH and HLS sources, which are v.redd.it links.

For v.redd.it URL's:
Appending either `/DASHPlaylist.mpd` or `/HLSPlaylist.m3u8` to the end of the URL will result in playable video. 

Note that HLS (at the time of writing this) considers every video as live since there's no real handling for m3u8 files. 

For example:
https://v.redd.it/8lukdvw6sti11/DASHPlaylist.mpd 
or
https://v.redd.it/8lukdvw6sti11/HLSPlaylist.m3u8
