### ISSUE TITLE
Unbanning user shows BANNED in user logs

### ISSUE THREAD

**Issue by QuillOmega0** [BTDev/BerryTube#55]
Upon unbanning a user, it registers in the log as a BANNED
![image](https://user-images.githubusercontent.com/2297709/119247257-d6bbdd00-bb3c-11eb-9b44-001277144175.png)

**Comment by jamesmanning** [comment]
Unbanning functions by calling banUser with a duration of 0

https://github.com/BTDev/BerryTube/blob/cbba99455be44fc4146ccaa4e5ad2938d153a77b/web/js/functions.js#L394-L396

but banUser's logging doesn't have any special treatment of duration == 0, so it logging-wise it's treated as permanent since duration isn't greater than 0

https://github.com/BTDev/BerryTube/blob/cbba99455be44fc4146ccaa4e5ad2938d153a77b/docker/node/server.js#L865-L867

PR #56 went with the minimal approach of just changing the verb to be logged.
